spring.application.name=backend
spring.data.mongodb.uri=mongodb://localhost:27017/SamarthSetu
server.port=8080
jwt.secret=ThisIsASampleSecretKeyForSmaranSetuJWTAuthChangeThisLater123
jwt.expirationMs=604800000