spring.application.name=backend
spring.data.mongodb.uri=mongodb+srv://yashsrivastav2603_db_user:C9bCmSIbeK1NGVT2@samarthsetu-cluster.mlugx9o.mongodb.net/test?retryWrites=true&w=majority
server.port=8080
jwt.secret=ThisIsASampleSecretKeyForSmaranSetuJWTAuthChangeThisLater123
jwt.expirationMs=604800000